title: bac0id's Blog
lang: zh-CN
markdown: kramdown

#baseurl: "/Blog"
#url: "https://bac0id.github.io"
#permalink: /:categories/:year-:month/:title
#permalink: /:year/:month/:day/:title
permalink: /:year-:month-:day/:title
#permalink: /Blog

# Conversion
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

timezone: Asia/Shanghai
copyright: bac0id 2021 build by jekyll
github_username: bac0id
github:
- is_project_page: True
- owner_name: bac0idD
- owner_url: https://github.com/bac0id/
theme: jekyll-theme-slate
