title: bac0id's Blog
theme: jekyll-theme-slate
baseurl: ""
url: ""
#permalink: /:categories/:year-:month/:title
timezone: Asia/Shanghai
copyright: bac0id 2021 build by jekyll
nav:
- name: 主页
  link: /
